import logging


def handle_error(error_message):
    logging.error(error_message)
